markdown: kramdown
permalink: /:year/:month/:day/:title
paginate: 10
exclude: [
 'node_modules',
 'bower_components',
 '.gitignore',
 'README.md',
 'gulpfile.js',
 'package.json',
 ]
sass:
 style: :compressed
